version: '3.9'

services:
    backend-nestjs:
        image: nestjs
        build:
            context: ./backend-nest
            dockerfile: ./Docker/Dockerfile-nest-dev
            args:
                - USERNAME=${NODE_CUSTOM_USERNAME}
                - NODE_WORKDIR=${NODE_WORKDIR}
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
        environment:
            - NODE_ENV=${NODE_ENV}
        user: "${USER_UID}:${USER_GID}"
        ports:
            - "3000:3000"
        volumes:
            - ./backend-nest:${NODE_WORKDIR}
        entrypoint: [ "tail", "-F", "anything" ]

    microsservico-golang:
        image: golang
        build:
            context: ./microsservico-golang
            dockerfile: ./Docker/Dockerfile-golang-dev
            args:
                - USERNAME=${GOLANG_CUSTOM_USERNAME}
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
                - GOLANG_WORKDIR=${GOLANG_WORKDIR}
        ports:
            - "8080:8080"
        volumes:
            - ./microsservico-golang
        entrypoint: [ "tail", "-F", "anything" ]

    db:
        image: bitnami/mongodb:5.0.17
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/bitnami/mongodb
        environment:
            - MONGODB_ROOT_PASSWORD=root
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_REPLICA_SET_KEY=123456
            - MONGODB_DATABASE=nest

    mysql: 
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=routes
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/mysql:/var/lib/mysql


volumes:
    mongodb_data:
        driver: local
