version: '3.9'

services:
    microsservico-golang:
        image: golang1
        build:
            context: ./microsservico-golang
            dockerfile: ./Docker/Dockerfile-golang
            # dockerfile: ./Docker/Dockerfile-golang-dev
            args:
                - USERNAME=${GOLANG_CUSTOM_USERNAME}
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
                - GOLANG_WORKDIR=${GOLANG_WORKDIR}
        ports:
            - "8080:8080"
        volumes:
            - ./microsservico-golang:${GOLANG_WORKDIR}
        # entrypoint: [ "tail", "-F", "anything" ]
    
    mysql: 
        image: mysql1
        build: 
            context: ./mysql
            dockerfile: ./Docker/Dockerfile
            args:
                - MYSQL_DATABASE=routes
                - MYSQL_ROOT_PASSWORD=root
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
        driver: local