version: '3.9'

services:
    backend-nestjs:
        build:
            context: ./backend-nest
            dockerfile: ./Docker/Dockerfile-nest-dev
            args:
                - USERNAME=${NODE_USERNAME}
                - NODE_WORKDIR=${NODE_WORKDIR}
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
        environment:
            - NODE_ENV=${NODE_ENV}
        user: "${USER_UID}:${USER_GID}"
        ports:
            - "${NODE_LOCAL_PORT}:3000"
        volumes:
            - ./backend-nest:${NODE_WORKDIR}
        entrypoint: [ "tail", "-F", "anything" ]
    
    frontend-nextjs:
        build:
            context: ./frontend-next
            dockerfile: ./Docker/Dockerfile-next-dev
            args:
                - USERNAME=${NODE_USERNAME}
                - NODE_WORKDIR=${NODE_WORKDIR}
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
        environment:
            - NODE_ENV=${NODE_ENV}
        user: "${USER_UID}:${USER_GID}"
        ports:
            - "${NEXT_LOCAL_PORT}:3000"
        volumes:
            - ./frontend-next:${NODE_WORKDIR}
        entrypoint: [ "tail", "-F", "anything" ]

    microsservico-golang:
        build:
            context: ./microsservico-golang
            dockerfile: ./Docker/Dockerfile-golang-dev
            args:
                - USERNAME=${GOLANG_USERNAME}
                - USER_UID=${USER_UID}
                - USER_GID=${USER_GID}
                - GOLANG_WORKDIR=${GOLANG_WORKDIR}
        ports:
            - "${GOLANG_LOCAL_PORT}:8080"
        volumes:
            - ./microsservico-golang
        entrypoint: [ "tail", "-F", "anything" ]

    db:
        image: bitnami/mongodb:5.0.17
        ports:
            - "${MONGODB_LOCAL_PORT}:27017"
        volumes:
            - mongodb_data:/bitnami/mongodb
        environment:
            - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
            - MONGODB_REPLICA_SET_MODE=${MONGODB_REPLICA_SET_MODE}
            - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
            - MONGODB_DATABASE=${MONGODB_DATABASE}

    mysql: 
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        ports:
            - "${MYSQL_LOCAL_PORT}:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mongodb_data:
        driver: local
    mysql_data:
        driver: local