# Template from https://github.com/Saluki/nestjs-template/blob/master/Dockerfile

FROM golang:1.21.0

ARG USERNAME=golang
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ARG GOLANG_WORKDIR=/home/${USERNAME}/app

RUN apt-get update && apt-get upgrade -y

# Create Non-root User
RUN groupadd --gid ${USER_GID} ${USERNAME} \
    && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME} \
    && mkdir /etc/sudoers.d \
    && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

USER ${USERNAME}
ENV SHELL=/bin/bash

WORKDIR "${GOLANG_WORKDIR}"