# Template from https://github.com/Saluki/nestjs-template/blob/master/Dockerfile

FROM node:18

ARG USERNAME
ARG USER_UID
ARG USER_GID
ARG NODE_WORKDIR

RUN apt-get update && apt-get upgrade -y
RUN npm install
RUN npx prisma generate

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && mkdir /etc/sudoers.d \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
    
USER ${USERNAME}
ENV HOME=/home/${USERNAME}
ENV SHELL=/bin/bash

WORKDIR ${NODE_WORKDIR}