# Template from https://github.com/Saluki/nestjs-template/blob/master/Dockerfile

FROM node:18

ARG USERNAME
ARG NODE_WORKDIR

RUN apt-get update && apt-get upgrade -y

USER ${USERNAME}
ENV SHELL=/bin/bash

COPY --chown=${USERNAME}:${USERNAME} ./nestjs "${NODE_WORKDIR}"

WORKDIR "${NODE_WORKDIR}"

RUN npm install
RUN npx prisma generate

CMD [ "npm", "run", "start" ]
