# Template from https://github.com/Saluki/nestjs-template/blob/master/Dockerfile

FROM node:18

ARG USERNAME
ARG USER_UID
ARG USER_GID
ARG NODE_WORKDIR

RUN apt-get update && apt-get upgrade -y
RUN npm install
RUN npx prisma generate

USER node
ENV SHELL=/bin/bash

WORKDIR ${NODE_WORKDIR}